
trigger:
- master

jobs:
- job: 'Test'
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      py27:
        PYTHON_VERSION: "2.7"
        ONNX_ML: 0
      py27-ml:
        PYTHON_VERSION: "2.7"
        ONNX_ML: 1
      py36:
        PYTHON_VERSION: "3.6"
        ONNX_ML: 0
      py36-debug:
        PYTHON_VERSION: "3.6"
        ONNX_ML: 0
        ONNX_DEBUG: 1
      py36-ml-debug:
        PYTHON_VERSION: "3.6"
        ONNX_ML: 1
        ONNX_DEBUG: 1
    maxParallel: 3

  steps:
    - script: |
      - task: Bash@3
        inputs:
          filePath: 'linux-ci.sh'
    displayName: 'Install dependencies'
