
trigger:
- master

jobs:
- job: 'Test'
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      py3:
        python.version: '3.6'
        PB_VERSION: 2.6.1
        ONNX_ML: 0
    maxParallel: 3

  steps:
  - script: sudo install -d -m 0777 /home/vsts/.conda/envs
    displayName: Fix Conda permissions
  - task: CondaEnvironment@1
    inputs:
      createCustomEnvironment: true
      environmentName: 'py$(python.version)'
      packageSpecs: 'python=$(python.version)'

  - script: |

      # install protobuf
      # wget -qO- "https://github.com/google/protobuf/releases/download/v${PB_VERSION}/protobuf-${PB_VERSION}.tar.gz" | tar -xz -C "$pb_dir" --strip-components 1
      # ./configure && make -j${NUMCORES} && make check && sudo make install && sudo ldconfig && cd -

      # Update all existing python packages
      python -m pip install --upgrade pip
      python -m pip install --quiet -U setuptools dos2unix protobuf

    displayName: 'Install dependencies'


  - script: |
      # onnx c++ API tests
      # export LD_LIBRARY_PATH="${top_dir}/.setuptools-cmake-build/:$LD_LIBRARY_PATH"
      # # do not use find -exec here, it would ignore the segement fault of gtest.
      # ./.setuptools-cmake-build/onnx_gtests
      # ./.setuptools-cmake-build/onnxifi_test_driver_gtests onnx/backend/test/data/node
      set ONNX_ML=${ONNX_ML}

      # onnx python API tests
      pip install --quiet pytest nbval
      pytest

      # lint python code
      pip install --quiet flake8
      flake8

      # check line endings to be UNIX
      find . -type f -regextype posix-extended -regex '.*\.(py|cpp|md|h|cc|proto|proto3|in)' | xargs dos2unix --quiet
      git status
      git diff --exit-code

      # check auto-gen files up-to-date
      python onnx/defs/gen_doc.py
      python onnx/gen_proto.py -l
      python onnx/gen_proto.py -l --ml
      python onnx/backend/test/stat_coverage.py
      backend-test-tools generate-data
      git status
      git diff --exit-code

    displayName: 'testing script'