trigger:
- master

jobs:

- job: 'Test'
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
    maxParallel: 3

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - script: conda create --yes --quiet --name py$(python.version) -c conda-forge python=$(python.version) numpy libprotobuf=3.11.3 protobuf=3.9.2 
    displayName: Create Anaconda environment

  - script: |
      call activate py$(python.version)
      python -m pip install --upgrade pip
      python -m pip install --quiet pytest nbval numpy
      
      cd onnx
      git submodule update --init --recursive
      set ONNX_BUILD_TESTS=1
      
      set USE_MSVC_STATIC_RUNTIME=0
      set CMAKE_ARGS=-DONNX_USE_PROTOBUF_SHARED_LIBS=ON -DProtobuf_USE_STATIC_LIBS=OFF -DONNX_USE_LITE_PROTO=ON
 
      python setup.py --quiet bdist_wheel --universal --dist-dir .
      python -m pip install 

      pytest
      python onnx/defs/gen_doc.py
      python onnx/gen_proto.py -l
      python onnx/gen_proto.py -l --ml

      rm -rf .setuptools-cmake-build
      pip install --quiet -e .[mypy]
      python setup.py typecheck

      git diff --exit-code
    displayName: Install and test onnx